### ISSUE TITLE
Missing wire in medbay - Mapping issue

### ISSUE THREAD

**Issue by YoteSanity** [ursamedium/ErosResearchPlatform#25]
There is a break in a wire in medbay, right where it crosses over a vent. It showed up after the update earlier today that adjusted the map a little, and appears to be an oversight. Every shift the engineer needs to walk in and fix it, or else the north side of medbay doesn't receive power.

Here is a screenshot of the exact location (care of the sexy shark engineer):

![space station 13 2016-05-31 170852](https://cloud.githubusercontent.com/assets/16764526/15690647/82830ee4-2752-11e6-92b9-728e836ed871.png)

**Comment by OrbisAnima** [comment]
Fixed with latest commit

**Comment by OrbisAnima** [comment]
(also, thanks for the report!)
