### ISSUE TITLE
Naughty bits overlap worn towels

### ISSUE THREAD

**Issue by Faire-Fuzzy** [ursamedium/ErosResearchPlatform#33]
Noticed this last night but was too lazy to post about it; Breasts and lower bits clip through a worn towel...that's about it.

#### Steps to reproduce
Wear a towel in your suit/belt slot.

**Comment by OrbisAnima** [comment]
Will be fixed in the coming patch, after we migrate to byond 510!

**Comment by OrbisAnima** [comment]
fixed!
