### ISSUE TITLE
Ghosts make footprints on snow

### ISSUE THREAD

**Issue by ursamedium** [ursamedium/ErosResearchPlatform#44]
#### Brief description of the issue
Title
#### What you expected to happen
To glide super secretly over snow as a ghost
#### What actually happened
Creepily left footprints on snow as ghost
#### Steps to reproduce
Be ghost.
Walk on snow.
#### Additional info:
Probably could creep people out like this.

**Comment by OrbisAnima** [comment]
Spoooooky scary snow!
