### ISSUE TITLE
Personal Communicator seems to be fucked up in the layout

### ISSUE THREAD

**Issue by OrbisAnima** [ursamedium/ErosResearchPlatform#6]
as said on the title, the Personal Communicator seems to be fucked up when you try to pick it from the loadout, the coders of polaris will probably tackle this issue on their own, but no reason to sit on our lazy asses and watch them work, either we disable those from loadout or make everyone spawn with one. or both.

**Comment by ursamedium** [comment]
Thinking both? Everyone spawning one would probably be ideal, then people who don't know they exist would just. Get one.

**Comment by OrbisAnima** [comment]
I think making people spawn with one communicator is awesome, now, I reproduced the bug, it appears with many loadouts if you are using a slot you didn't saved
