### ISSUE TITLE
Boobs on back

### ISSUE THREAD

**Issue by AliciaJewel** [ursamedium/ErosResearchPlatform#81]
#### Brief description of the issue
All but "Very Large Breasts" appear on the backs of topless characters.

#### What you expected to happen
For my character not to have breasts on their back

#### What actually happened
My character had breasts on their back

#### Steps to reproduce
1. Go into character creation
2. Give a character any breast size besides very large
3. Witness the four-boobed monstrosity

#### Additional info:
 - **Server Revision**: Revision unknown
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by ursamedium** [comment]
Leaving this open, because my fix is horrible.
