### ISSUE TITLE
Cryo Doesnt Cryo

### ISSUE THREAD

**Issue by ursamedium** [ursamedium/ErosResearchPlatform#9]
it holds bodies forever... ever..ever...ever...

**Comment by OrbisAnima** [comment]
Will check it now that we have polaris code, test it with a 50 clone damage thing, at 70k, wich clonexodane and cryoxodane, and will see what happens

**Comment by OrbisAnima** [comment]
Yep, it's working now in the Polaris code, just be careful not to use the dummy mobs, and use the alien ones like tajara for testing... it's somehow inmortal. fucking dummy.
